package com.JIRSend.ui;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class MainChatSystemFrame extends JFrame {
    private JPanel contentPane;
    private JPanel headPane;
    private JPanel bodyPane;
    private JPanel Footer;
    private JPanel contactsSection;
    private JPanel chatSection;
    private JPanel chatContent;
    private JPanel contactsContent;
    private JLabel contactsLabel;
    private JPanel chatContactName;
    private JPanel SendMessageSection;
    private JScrollPane messagesScroll;
    private JButton sendMessageButton;
    private JScrollPane messageToSendScroll;
    private JTextPane inputMessage;
    private JLabel chatContactLabel;
    private JTextField jackTextField;
    private JScrollPane contactsListScroll;
    private JPanel contactsList;
    private JButton sButton;
    private JPanel messagesList;
    private JPanel contactElement;
    private JLabel contactName;
    private JPanel messageElement;
    private JLabel messageAuthor;
    private JTextPane messageContent;
    private JLabel chatSystemName;

    public MainChatSystemFrame() {
        setTitle("JIR Send");
        setSize(550, 300);
        setContentPane(contentPane);

        setVisible(true);
    }

    // public static void main(String[] args) {
    //     MainChatSystemFrame mainFrame = new MainChatSystemFrame();
    // }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), 0, 0));
        headPane = new JPanel();
        headPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), 0, 0));
        headPane.setBackground(new Color(-11842224));
        contentPane.add(headPane, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(24, 25), null, 0, false));
        chatSystemName = new JLabel();
        chatSystemName.setBackground(new Color(-11842224));
        Font chatSystemNameFont = this.$$$getFont$$$("Monospaced", Font.BOLD, -1, chatSystemName.getFont());
        if (chatSystemNameFont != null) chatSystemName.setFont(chatSystemNameFont);
        chatSystemName.setForeground(new Color(-394241));
        chatSystemName.setText("JIRSend");
        headPane.add(chatSystemName, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        headPane.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        bodyPane = new JPanel();
        bodyPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), 0, 0));
        bodyPane.setBackground(new Color(-14342358));
        contentPane.add(bodyPane, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(24, 353), null, 0, false));
        contactsSection = new JPanel();
        contactsSection.setLayout(new CardLayout(0, 0));
        contactsSection.setBackground(new Color(-13223877));
        bodyPane.add(contactsSection, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(121, 0), null, 0, false));
        contactsContent = new JPanel();
        contactsContent.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        contactsContent.setBackground(new Color(-13223877));
        contactsSection.add(contactsContent, "Card1");
        contactsLabel = new JLabel();
        contactsLabel.setBackground(new Color(-13288643));
        Font contactsLabelFont = this.$$$getFont$$$("Monospaced", Font.BOLD, 22, contactsLabel.getFont());
        if (contactsLabelFont != null) contactsLabel.setFont(contactsLabelFont);
        contactsLabel.setForeground(new Color(-394241));
        contactsLabel.setText("Contacts");
        contactsContent.add(contactsLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        contactsListScroll = new JScrollPane();
        contactsListScroll.setBackground(new Color(-13223877));
        contactsContent.add(contactsListScroll, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        contactsList = new JPanel();
        contactsList.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        contactsList.setBackground(new Color(-13223877));
        contactsListScroll.setViewportView(contactsList);
        contactElement = new JPanel();
        contactElement.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        contactElement.setBackground(new Color(-13288643));
        contactsList.add(contactElement, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        contactName = new JLabel();
        Font contactNameFont = this.$$$getFont$$$("Monospaced", Font.BOLD, -1, contactName.getFont());
        if (contactNameFont != null) contactName.setFont(contactNameFont);
        contactName.setForeground(new Color(-854792));
        contactName.setText("John");
        contactElement.add(contactName, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        contactsList.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        chatSection = new JPanel();
        chatSection.setLayout(new CardLayout(0, 0));
        chatSection.setBackground(new Color(-14671323));
        bodyPane.add(chatSection, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        chatContent = new JPanel();
        chatContent.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        chatContent.setBackground(new Color(-14671323));
        chatSection.add(chatContent, "Card1");
        chatContactName = new JPanel();
        chatContactName.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        chatContactName.setBackground(new Color(-12371388));
        chatContactName.setEnabled(true);
        chatContent.add(chatContactName, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        chatContactLabel = new JLabel();
        Font chatContactLabelFont = this.$$$getFont$$$("Monospaced", Font.BOLD, 36, chatContactLabel.getFont());
        if (chatContactLabelFont != null) chatContactLabel.setFont(chatContactLabelFont);
        chatContactLabel.setForeground(new Color(-394241));
        chatContactLabel.setIconTextGap(10);
        chatContactLabel.setText("John");
        chatContactName.add(chatContactLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        SendMessageSection = new JPanel();
        SendMessageSection.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        SendMessageSection.setBackground(new Color(-13816014));
        chatContent.add(SendMessageSection, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(-1, 80), new Dimension(-1, 300), 0, false));
        sendMessageButton = new JButton();
        sendMessageButton.setBackground(new Color(-11842224));
        sendMessageButton.setBorderPainted(true);
        Font sendMessageButtonFont = this.$$$getFont$$$("Monospaced", Font.BOLD, 8, sendMessageButton.getFont());
        if (sendMessageButtonFont != null) sendMessageButton.setFont(sendMessageButtonFont);
        sendMessageButton.setForeground(new Color(-854792));
        sendMessageButton.setText("SEND >");
        SendMessageSection.add(sendMessageButton, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        messageToSendScroll = new JScrollPane();
        messageToSendScroll.setBackground(new Color(-13816014));
        SendMessageSection.add(messageToSendScroll, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        inputMessage = new JTextPane();
        inputMessage.setBackground(new Color(-13816014));
        inputMessage.setCaretColor(new Color(-3684409));
        inputMessage.setDragEnabled(true);
        Font inputMessageFont = this.$$$getFont$$$("Monospaced", -1, -1, inputMessage.getFont());
        if (inputMessageFont != null) inputMessage.setFont(inputMessageFont);
        inputMessage.setForeground(new Color(-854792));
        inputMessage.setName("Enter your message here");
        inputMessage.setSelectedTextColor(new Color(-394241));
        inputMessage.setText("");
        inputMessage.setToolTipText("Enter your message here");
        messageToSendScroll.setViewportView(inputMessage);
        messagesScroll = new JScrollPane();
        messagesScroll.setAutoscrolls(true);
        messagesScroll.setBackground(new Color(-14671323));
        messagesScroll.setHorizontalScrollBarPolicy(31);
        chatContent.add(messagesScroll, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        messagesList = new JPanel();
        messagesList.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(1, 1, 1, 1), 2, 2));
        messagesList.setBackground(new Color(-14671323));
        messagesList.setForeground(new Color(-854792));
        messagesScroll.setViewportView(messagesList);
        messageElement = new JPanel();
        messageElement.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        messageElement.setBackground(new Color(-13816014));
        messagesList.add(messageElement, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        messageAuthor = new JLabel();
        messageAuthor.setBackground(new Color(-13816014));
        Font messageAuthorFont = this.$$$getFont$$$("Monospaced", Font.BOLD, -1, messageAuthor.getFont());
        if (messageAuthorFont != null) messageAuthor.setFont(messageAuthorFont);
        messageAuthor.setForeground(new Color(-394241));
        messageAuthor.setText("Author: ");
        messageElement.add(messageAuthor, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        messageContent = new JTextPane();
        messageContent.setBackground(new Color(-13816014));
        messageContent.setDisabledTextColor(new Color(-854792));
        messageContent.setEditable(false);
        messageContent.setEnabled(false);
        Font messageContentFont = this.$$$getFont$$$("Monospaced", -1, -1, messageContent.getFont());
        if (messageContentFont != null) messageContent.setFont(messageContentFont);
        messageContent.setForeground(new Color(-854792));
        messageContent.setSelectedTextColor(new Color(-394241));
        messageContent.setText("Message sent\nin several lines.");
        messageElement.add(messageContent, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer3 = new com.intellij.uiDesigner.core.Spacer();
        messagesList.add(spacer3, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        Footer = new JPanel();
        Footer.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), 0, 0));
        Footer.setBackground(new Color(-11842224));
        contentPane.add(Footer, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(24, 25), null, 0, false));
        jackTextField = new JTextField();
        jackTextField.setBackground(new Color(-11842224));
        jackTextField.setCaretColor(new Color(-3684409));
        Font jackTextFieldFont = this.$$$getFont$$$("Monospaced", Font.BOLD, -1, jackTextField.getFont());
        if (jackTextFieldFont != null) jackTextField.setFont(jackTextFieldFont);
        jackTextField.setForeground(new Color(-854792));
        jackTextField.setHorizontalAlignment(4);
        jackTextField.setSelectedTextColor(new Color(-394241));
        jackTextField.setText("Jack");
        jackTextField.setToolTipText("Change your username");
        Footer.add(jackTextField, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), new Dimension(250, -1), 0, false));
        sButton = new JButton();
        sButton.setBackground(new Color(-11842224));
        sButton.setForeground(new Color(-394241));
        sButton.setText("S");
        Footer.add(sButton, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, new Dimension(20, 20), 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
